/** @generated by kitter.js */
export const kitterConfig = {
  styles: {
    documentation: {
      maxWidth: '1000px',
      className: '',
    },
    scrollToTop: {
      textClassName: '',
      iconClassName: '',
      iconColor: 'black',
      textOverride: 'table of contents',
    },
    page: {
      className: '',
      center: false,
    },
    pageTitle: {
      className: '',
    },
    pageDescription: {
      className: '',
    },
    pageSection: {
      titleClassName: '',
    },
    documentContents: {
      className: '',
    },
  },
};
